AUTOMAKE_OPTIONS = 1.6
MOSTLYCLEANFILES     = *~ \\\#* .*~ .\\\#*
MAINTAINERCLEANFILES = Makefile.in

debug:
	@$(MAKE) CFLAGS="$(DEBUG_CFLAGS)"

debug-install: install-debug

install-debug:
	@$(MAKE) CFLAGS="$(DEBUG_CFLAGS)" install
